services:
  - type: web
    name: movie-theater-booking
    env: python
    region: oregon
    plan: free
    branch: main
        buildCommand: cd cs4300/homework2 && bash build.sh
    startCommand: cd cs4300/homework2 && gunicorn movie_theater_booking.wsgi
    autoDeploy: true
    
    envVars:
      - key: SECRET_KEY
        value: ""
       
      - key: DEBUG
        value: "False"
        
      - key: DATABASE_URL
        value: ""
        
