services:
  - type: web
    name: movie-theater-booking
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn movie_theater_booking.wsgi
    autoDeploy: true
    
    envVars:
      - key: SECRET_KEY
        value: ""
        sync: false
      - key: DEBUG
        value: "False"
        sync: false
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
        sync: false
      - key: DATABASE_URL
        value: ""
        sync: false
